In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
print("Orginal array:",arr)
x=np.where(arr==4)
print("\nIndexes where the value is 4:\n",x)

Orginal array: [1 2 3 4 5 4 4]

Indexes where the value is 4:
 (array([3, 5, 6]),)


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr)

In [ ]:
arr = np.array([3, 2,0,1])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))
arr = np.array([[3, 2, 4], [5, 0, 1]])
print("\nOriginal array:\n",arr)
print("nSorted array:\n",np.sort(arr))


Original array: [3 2 0 1]

Sorted array: [0 1 2 3]

Original array:
 [[3 2 4]
 [5 0 1]]
nSorted array:
 [[2 3 4]
 [0 1 5]]


In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print("\nOriginal array:",arr)
print("\nFilter array:condition->42:",filter_arr)
print("nNew array:",newarr)


Original array: [41 42 43 44]

Filter array:condition->42: [False False  True  True]
nNew array: [43 44]
