In [1]:
import numpy as np
arr = np.array([[-1, 2, 0, 4], [4, -0.5, 6, 0], [2.6, 0, 7, 8], [3, -7, 4, 2.0]])
print("Original array:\n", arr)

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [2]:
print("\nEvery other rows: \n", arr[0:3:2])


Every other rows: 
 [[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [3]:
arra = np.array([1, 2, 3])
arrb = np.array([4, 5, 6])
arr = np.concatenate((arra, arrb))
print("\n Original arrays:\n",arra,arrb) 
print("\n Joined array:\n",arr)


 Original arrays:
 [1 2 3] [4 5 6]

 Joined array:
 [1 2 3 4 5 6]


In [4]:
#Horizondal join
arr= np.hstack((arra, arrb))
print("\n Horizondal joining:\n",arr)


 Horizondal joining:
 [1 2 3 4 5 6]


In [5]:
arr = np.vstack((arra, arrb))
print("\n Vertical joining:\n", arr)


 Vertical joining:
 [[1 2 3]
 [4 5 6]]


In [6]:
arr = np.dstack((arra, arrb))
print("\n Depth joining:\n",arr)


 Depth joining:
 [[[1 4]
  [2 5]
  [3 6]]]


In [7]:
arr= np.array([1, 2, 3, 4, 5, 6]) 
newarr= np.array_split(arr, 3)
print("\nOriginal Array:\n",arr)
print("\nSplitted array:\n",newarr)
print("\nSplitted array in another form:\n")
print(newarr[0])
print(newarr[1])
print(newarr[2])


Original Array:
 [1 2 3 4 5 6]

Splitted array:
 [array([1, 2]), array([3, 4]), array([5, 6])]

Splitted array in another form:

[1 2]
[3 4]
[5 6]
